language: go
go:
  - 1.3
  - 1.4
  - tip

install:
  - go get -v -t ./...

after_script:
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi

script:
  - go test -v ./...
